# Generated by Django 3.0.5 on 2021-01-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('specialization', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='laboratory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('contact_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.TextField()),
                ('mobile', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='receptionist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('hospital', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='timeslot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('isActive', models.BooleanField()),
                ('day', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='labReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.FileField(upload_to=None)),
                ('upload_date', models.DateField()),
                ('upload_time', models.TimeField()),
                ('doneBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.laboratory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.patient')),
            ],
        ),
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField(blank=True, null=True)),
                ('createdAt', models.DateField()),
                ('updatedAt', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('prescription', models.CharField(blank=True, max_length=2000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.patient')),
            ],
        ),
    ]
