# Generated by Django 3.0.5 on 2021-01-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timmings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
    ]
